version: '3.8'

services:
  frontend:
    image: danielaharon555/chat_bot_frontend:1.0.0
    ports:
      - "8001:8001"
    depends_on:
      - backend
    networks:
      - chat-network

  backend:
    image: danielaharon555/chat_bot_backend:1.0.0
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge




